# keep our base image as small as possible
FROM nginx/unit:1.17.0-php7.3

# port used by the listener in config.json
EXPOSE 8080

# application setup
COPY ./docker/config.json /docker-entrypoint.d/

RUN apt-get update \
    && apt-get install -y \
    php7.3-mysql \
    make \
    php7.3-dev \
    php-pear \
    unixodbc-dev \
    gnupg2 

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list\
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y \
    msodbcsql17 \
    && pecl install \
    sqlsrv \
    pdo_sqlsrv \
    && printf "; priority=20\nextension=sqlsrv.so\n" > /etc/php/7.3/mods-available/sqlsrv.ini \
    && printf "; priority=30\nextension=pdo_sqlsrv.so\n" > /etc/php/7.3/mods-available/pdo_sqlsrv.ini \
    && phpenmod -v 7.3 sqlsrv pdo_sqlsrv